// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShiftManagementSystem.Models;

[Table("HolidayCache")]
[Index("HolidayDate", Name = "IX_HolidayCache_Date")]
[Index("CacheYear", Name = "IX_HolidayCache_Year")]
[Index("HolidayDate", Name = "UQ__HolidayC__F1ADD9D10E9C1ACB", IsUnique = true)]
public partial class HolidayCache
{
    [Key]
    public int HolidayId { get; set; }

    public DateOnly HolidayDate { get; set; }

    [Required]
    [StringLength(100)]
    public string HolidayName { get; set; }

    [Required]
    [StringLength(50)]
    public string HolidayCategory { get; set; }

    public string Description { get; set; }

    public bool? IsOfficialHoliday { get; set; }

    public int CacheYear { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdatedFromApi { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }
}