// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ShiftManagementSystem.Models;

public partial class ScheduleDBContext : DbContext
{
    public ScheduleDBContext(DbContextOptions<ScheduleDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<HolidayCache> HolidayCaches { get; set; }

    public virtual DbSet<ShiftQuotaLimit> ShiftQuotaLimits { get; set; }

    public virtual DbSet<ShiftRecord> ShiftRecords { get; set; }

    public virtual DbSet<ShiftStatistic> ShiftStatistics { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<HolidayCache>(entity =>
        {
            entity.HasKey(e => e.HolidayId).HasName("PK__HolidayC__2D35D57A33DD4D66");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsOfficialHoliday).HasDefaultValue(true);
        });

        modelBuilder.Entity<ShiftQuotaLimit>(entity =>
        {
            entity.HasKey(e => e.QuotaId).HasName("PK__ShiftQuo__AE96C9C240E434E7");

            entity.Property(e => e.CurrentShiftCount).HasDefaultValue(0);
            entity.Property(e => e.IsVerified).HasDefaultValue(false);
            entity.Property(e => e.MaxShifts).HasDefaultValue(15);
            entity.Property(e => e.MinShifts).HasDefaultValue(6);

            entity.HasOne(d => d.User).WithMany(p => p.ShiftQuotaLimits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ShiftQuot__UserI__6477ECF3");
        });

        modelBuilder.Entity<ShiftRecord>(entity =>
        {
            entity.HasKey(e => e.ShiftId).HasName("PK__ShiftRec__C0A83881700B54C0");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.ShiftRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ShiftReco__UserI__5CD6CB2B");
        });

        modelBuilder.Entity<ShiftStatistic>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__ShiftSta__3A162D3E5352B959");

            entity.Property(e => e.LastCalculatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.TotalShiftDays).HasDefaultValue(0);

            entity.HasOne(d => d.User).WithMany(p => p.ShiftStatistics)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ShiftStat__UserI__6A30C649");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C809953E5");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}