// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShiftManagementSystem.Models;

[Index("UserId", "StatYear", "StatMonth", Name = "UQ__ShiftSta__AFFF0D7C214470D5", IsUnique = true)]
public partial class ShiftStatistic
{
    [Key]
    public int StatId { get; set; }

    public int UserId { get; set; }

    public int StatYear { get; set; }

    public int? StatMonth { get; set; }

    public int? TotalShiftDays { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastCalculatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ShiftStatistics")]
    public virtual User User { get; set; }
}