// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShiftManagementSystem.Models;

[Index("ShiftDate", "ShiftStatus", Name = "IX_ShiftRecords_DateAndStatus")]
[Index("UserId", "ShiftDate", Name = "IX_ShiftRecords_UserAndDate")]
[Index("UserId", "ShiftDate", Name = "UQ__ShiftRec__817FA3601E5E998A", IsUnique = true)]
public partial class ShiftRecord
{
    [Key]
    public int ShiftId { get; set; }

    public int UserId { get; set; }

    public DateOnly ShiftDate { get; set; }

    [Required]
    [StringLength(20)]
    public string ShiftStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ShiftRecords")]
    public virtual User User { get; set; }
}