// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShiftManagementSystem.Models;

[Index("UserId", "YearMonth", Name = "UQ__ShiftQuo__CFFDC222F744D14C", IsUnique = true)]
public partial class ShiftQuotaLimit
{
    [Key]
    public int QuotaId { get; set; }

    public int UserId { get; set; }

    [Required]
    [StringLength(7)]
    public string YearMonth { get; set; }

    public int? MinShifts { get; set; }

    public int? MaxShifts { get; set; }

    public int? CurrentShiftCount { get; set; }

    public bool? IsVerified { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ShiftQuotaLimits")]
    public virtual User User { get; set; }
}