// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShiftManagementSystem.Models;

[Index("Username", Name = "UQ__Users__536C85E4542F822F", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    public string PasswordHash { get; set; }

    [Required]
    public string PasswordSalt { get; set; }

    [Required]
    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    public string Role { get; set; }

    public bool? IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<ShiftQuotaLimit> ShiftQuotaLimits { get; set; } = new List<ShiftQuotaLimit>();

    [InverseProperty("User")]
    public virtual ICollection<ShiftRecord> ShiftRecords { get; set; } = new List<ShiftRecord>();

    [InverseProperty("User")]
    public virtual ICollection<ShiftStatistic> ShiftStatistics { get; set; } = new List<ShiftStatistic>();
}